### ISSUE TITLE
Using padding object in table cell

### ISSUE THREAD

**Issue by d3v1an7** [Robert-Fairley/apple-news-format#53]
Hey! First off, thanks heaps for this, super helpful :)
I'm using this in a non-standard way, vanilla JS + JSdoc/checkJs -- feel free to close if that is the cause.

Code example:
```
/**
 * @param {object} params
 * @param {string} params.text
 * @returns {import('apple-news-format').AppleNews.HTMLTable} Valid HTMLTable object.
 */
function generateKicker({ text }) {
  return {
    role: "htmltable",
    html: `<table><tr><td>Foo</td><td>${text}</td></tr></table>`,
    style: {
      tableStyle: {
        cells: {
          textStyle: {
            textTransform: "uppercase",
          },
          conditional: [
            {
              selectors: [{ descriptor: null, evenColumns: true }],
              backgroundColor: "#E9FF5C",
              padding: {
                left: 6,
                right: 4,
                bottom: 2,
                top: 2,
              },
            },
            {
              selectors: [{ descriptor: null, oddColumns: true }],
              width: 1,
              padding: {
                left: 12,
              },
            },
          ],
        },
      },
    },
  };
}
```

I'm getting the following error on `padding`:
> Type '{ left: number; right: number; bottom: number; top: number; }' is not assignable to type 'string | number'.ts(2322)
table-cell-style-base.d.ts(10, 5): The expected type comes from property 'padding' which is declared here on type 'ConditionalTableCellStyle'

![Screenshot 2024-06-04 at 1 07 34 PM](https://github.com/Robert-Fairley/apple-news-format/assets/4087799/a7591a2c-1742-4792-ad13-556b42f8c8ab)

I believe the padding object should be supported, as per: https://developer.apple.com/documentation/apple_news/padding

**Comment by Robert-Fairley** [comment]
Hi Ben,

Sorry for the delay in getting back to you on this. Pretty busy these days and not much time spent in the publish world as of late.

I just double checked the `TableCellStyleBase` interface and it looks like it is configured to accept a padding object.

https://github.com/Robert-Fairley/apple-news-format/blob/0d8ce7ff0f953482abdc63e34ab603dad02178cb/src/styles/component-styles/table-cell-style-base.ts#L14-L24

I haven't worked with checkJs before, so it's possible this is an issue related to its own parser. But it also looks like that is VSCode's TypeScript language server raising that error—do you want to double check that you have the latest package version installed? (Version `1.1.0` was published ~2 months ago)

Let me know if this is persisting for you. It's also open to (and appreciative of) pull requests—if you see anything that needs updated or improving.

**Comment by Robert-Fairley** [comment]
Hi Ben, I wrote a response already but I was mistaken. It looks like the type needs a quick update. I'll notify you again here  when there's a new patch published

**Comment by Robert-Fairley** [comment]
Sorry @d3v1an7 ! I can't believe I forgot to respond until now. Life has been consuming in strange ways.
This fix finally went out in September with https://github.com/Robert-Fairley/apple-news-format/releases/tag/1.1.1

Always happy to receive PR's if you catch stuff like this in the future! Cheers
